# Site settings
title: Refugee Emojis
email: 
description: > # this means to ignore newlines until "baseurl:"
  Refugee Emojis are coming soon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://refugeeemojis.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'Readme.md']

assets:
  js_compressor: uglifier
  css_compressor: sass
